name: iotfiware

services:
  # Data bases
  mongo-db:
    image: mongo:4.4
    restart: always
    command: --nojournal
    hostname: mongo-db
    container_name: fiware-mongo
    networks:
      - default  
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  # Orion Context Broker
  orion:
    image: fiware/orion:latest
    restart: always
    hostname: orion
    container_name: fiware-orion
    networks:
      - default  
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-db:27017 -corsOrigin __ALL -corsMaxAge 600

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    hostname: mosquitto
    container_name: fiware-mosquitto
    networks:
      - default  
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # IoT Agent (MQTT to NGSI)
  iot-agent:
    image: fiware/iotagent-ul:latest
    restart: always
    hostname: iot-agent
    container_name: fiware-iot-agent
    networks:
      - default
    depends_on:
      - mongo-db
      - mosquitto
    expose:
      - "4041"
    ports:
      - "4041:4041"
    environment:
      # Mongo
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentul
      # Orion
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_CB_NGSI_VERSION=v2
      # MQTT
      - IOTA_DEFAULT_TRANSPORT=MQTT
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_NORTH_PORT=4041
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_AUTOCAST=true
      - IOTA_PROVIDER_URL=http://iot-agent:4041
  
      - IOTA_DEFAULT_RESOURCE=/iot/d

networks:
  default:
    labels:
      org.fiware: 'fiware'

volumes:
  db-data: ~